env: matrix_game

env_args:
  n_agents: 2
  n_actions: 2
  map_name: "matrix"
  episode_limit: 1
  obs_last_action: False
  state_last_action: False

test_greedy: True
test_nepisode: 32
test_interval: 1000
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 2050000
